import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar'
import 'animate.css';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Portafolio Rodrigo Olivera',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-black/90 w-full relative">
        {<Navbar />}
        {children}
      </body>
    </html>
  )
}
